# Generated by Django 5.1.1 on 2024-10-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_services_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(default='ServicesImages/bakr.jpg', upload_to='ServicesImages/'),
        ),
    ]
