# Generated by Django 5.1.1 on 2024-10-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service_servicedata_servicepoint_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepoint',
            name='service_data',
        ),
        migrations.AddField(
            model_name='service',
            name='paragraph',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subTitle',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceData',
        ),
        migrations.DeleteModel(
            name='ServicePoint',
        ),
    ]
