# Generated by Django 5.1.1 on 2024-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AlterField(
            model_name='news',
            name='paragraph',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragraph',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
