# Generated by Django 5.1.1 on 2024-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_service_icon_alter_news_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
