# Generated by Django 5.1.1 on 2024-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ServicesImages/')),
                ('icon', models.ImageField(upload_to='ServicesImages/')),
                ('subtittle', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
    ]
