# Generated by Django 5.1.1 on 2024-10-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bgImg', models.ImageField(upload_to='bg_images/')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('txt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTitle', models.TextField()),
                ('paragraph', models.TextField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_data', to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('service_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app.servicedata')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
