# Generated by Django 5.1.1 on 2024-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_servicepoint_service_data_service_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('projectImg', models.ImageField(upload_to='project_images/')),
                ('projectTitle', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
            ],
        ),
    ]
