# Generated by Django 5.1.1 on 2024-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
